spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 5555
    driver-class-name: com.mysql.jdbc.Driver
  # 配置 MyBatis-Plus
#  mybatis-plus:
#    configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    # 实体类包名，多个用逗号分隔
##    typeAliasesPackage: com.fh.code.entity
#    # MyBatis XML 文件的位置
#    mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
